on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Update README.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Run benchmark
        run:|
          ls
          cd benchmark
          make report.md
      - name: Create README.md
        run:|
          ls
          ls benchmark
          cat README.md.template | sed -e "s^@@BENCHMARK@@^$(cat ./benchmark/report.md | awk '{printf "%s\\n", $0}')^g" > README.md
      - name: check
        run: ls
      - name: Push README.md
        run:|
          git add README.md
          git commit -m 'update README.md'
          git push origin main
